### Import libraries

In [168]:
import numpy as np
import cv2
import os

**Parameter**

In [169]:
folder_path = "trafficSignData"
label_file = 'labels.csv'
imageDimesions = (32,32)
ratio = 0.2

### Load the images and number of classes

In [170]:
images = []
classNumber = []

In [171]:
# get the path of the traffic data
myList = os.listdir(folder_path)
print("View each classes in traffic folder :", myList, "\n")

# get the number of classes (number of folder)
lengthOfClasses = len(myList)
print("Total length of classes :", lengthOfClasses, "\n")


View each classes in traffic folder : ['50', '57', '32', '35', '56', '51', '34', '33', '20', '18', '27', '9', '0', '11', '7', '29', '16', '42', '45', '6', '28', '17', '1', '10', '19', '26', '8', '21', '44', '43', '38', '36', '31', '54', '53', '30', '37', '39', '52', '55', '46', '41', '48', '24', '23', '4', '15', '3', '12', '49', '40', '47', '2', '13', '5', '14', '22', '25'] 

Total length of classes : 58 



### Iterate to load the images and classes

In [172]:
print("Iterating to load images & classes\n")
# iterate 0 to length of classes (58)
for x in range(0, lengthOfClasses): # x is folder
    imagesList = os.listdir(os.path.join(folder_path, str(x))) # each (x) folder in trafficSignData 
    for img in imagesList:
        currentImage = cv2.imread(folder_path + "/" + str(x) + "/" + img) # trafficSignData --> x folder --> img = images
        if currentImage is not None:  # Check image is read
            currentImage = cv2.resize(currentImage, imageDimesions) # Resize to the dimensions to 32 X 32 pixels
            images.append(currentImage)
            classNumber.append(x)
        else:
            print(f"It is wrong folder path {folder_path}")
    print(x, end=" ")

Iterating to load images & classes

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 

### Convert list to numpy array

In [173]:
# Convert list to numpy array
images = np.array(images)
classNumber = np.array(classNumber)

**Result**

In [174]:
print(images)
print(classNumber)

[[[[ 41  39  32]
   [ 38  39  31]
   [ 38  38  30]
   ...
   [155 153 151]
   [190 190 190]
   [192 192 192]]

  [[ 40  40  30]
   [ 38  38  32]
   [ 40  38  31]
   ...
   [151 150 147]
   [189 190 190]
   [189 189 189]]

  [[ 41  41  31]
   [ 39  39  30]
   [ 38  39  30]
   ...
   [145 146 141]
   [188 188 188]
   [185 185 185]]

  ...

  [[194 189 181]
   [195 190 176]
   [196 189 178]
   ...
   [121  49   7]
   [123  51   5]
   [121  50   8]]

  [[194 185 171]
   [193 184 173]
   [194 185 172]
   ...
   [165 158 151]
   [167 160 150]
   [167 162 153]]

  [[179 174 166]
   [179 174 166]
   [183 176 168]
   ...
   [125  55  13]
   [126  56  12]
   [127  55  13]]]


 [[[126  64  21]
   [138  91  58]
   [143 102  71]
   ...
   [165 155 142]
   [176 180 185]
   [162 166 170]]

  [[139 110  93]
   [154 140 129]
   [120  78  58]
   ...
   [164 159 153]
   [174 178 183]
   [169 171 171]]

  [[135  97  75]
   [145 114 101]
   [140 126 119]
   ...
   [157 162 164]
   [185 188 192]
   [179 179

**Check images shape and classNumber**

- the first number is number of images
- 32 x 32 images
- 3 mean RGB 3 channals

In [175]:
print(images.shape)
print(classNumber.shape)

(4170, 32, 32, 3)
(4170,)


### Data Spliting

**import train_test_split**

In [176]:
from sklearn.model_selection import train_test_split

### Spliting the data
- split the array images, classNumber, set the test size for exmaple 0.2
- test_size = 0.2 means that training will be 0.8 percent and test will be 0.2, so 20% testing and 80% training

In [177]:
X_train, X_test, y_train, y_test = train_test_split(images, classNumber, test_size=ratio)

**Check whether it is split or not (train, test)**
- by using shape function

In [178]:
print("After spliting for images for traning")
print(X_train.shape)
print("After spliting for images for testing")
print(X_test.shape)

print("\n After spliting for classNUmber for traning & testing")
print(y_train.shape)
print(y_test.shape)

After spliting for images for traning
(3336, 32, 32, 3)
After spliting for images for testing
(834, 32, 32, 3)

 After spliting for classNUmber for traning & testing
(3336,)
(834,)


**Get the X_validation**
- to get X_validation use the 80% of images array which is X_train and use y_train

In [179]:
X_train, X_validation, y_train, y_validation = train_test_split(X_train, y_train, test_size=ratio)
print('Get the X_validation')
print(X_validation.shape)

Get the X_validation
(668, 32, 32, 3)


**Print X_train, X_test, and X_validation**

In [180]:
print(X_train.shape)
print(X_test.shape)
print(X_validation.shape)

(2668, 32, 32, 3)
(834, 32, 32, 3)
(668, 32, 32, 3)


**What inside the X and Y**
- X_train contain = actual images, Y_train contain = the ids of each image

In [182]:
# show the all the index numbers which are class number 0
print(np.where(y_train==0))
# total length of classNumber 0
print(len(np.where(y_train==0)[0]))

print("Total number of images for each Class")
for x in range(0,lengthOfClasses):
    print(f"Class {x}: {len(np.where(y_train == x)[0])}")

(array([   4,    5,   60,   63,   94,   97,  109,  114,  135,  149,  214,
        225,  242,  320,  326,  337,  344,  358,  363,  385,  438,  512,
        546,  549,  581,  596,  625,  654,  658,  666,  675,  718,  811,
        891,  915,  925,  944,  975, 1049, 1108, 1131, 1159, 1187, 1234,
       1240, 1289, 1314, 1335, 1347, 1380, 1424, 1437, 1451, 1511, 1571,
       1715, 1743, 1753, 1790, 1793, 1799, 1906, 1910, 1912, 1913, 1930,
       1986, 1989, 2085, 2200, 2209, 2251, 2341, 2347, 2418, 2433, 2453,
       2465, 2503, 2558, 2560, 2573, 2585]),)
83
Total number of images for each Class
Class 0: 83
Class 1: 25
Class 2: 50
Class 3: 156
Class 4: 54
Class 5: 113
Class 6: 46
Class 7: 95
Class 8: 6
Class 9: 2
Class 10: 47
Class 11: 89
Class 12: 66
Class 13: 24
Class 14: 87
Class 15: 18
Class 16: 100
Class 17: 85
Class 18: 6
Class 19: 2
Class 20: 10
Class 21: 7
Class 22: 7
Class 23: 6
Class 24: 66
Class 25: 2
Class 26: 86
Class 27: 19
Class 28: 273
Class 29: 28
Class 30: 106
Class 31: 2