### Import libraries

In [7]:
import numpy as np
import cv2
import os

**Parameter**

In [8]:
folder_path = "trafficSignData"
label_file = 'labels.csv'
imageDimesions = (32,32)

### Load the images and number of classes

In [11]:
images = []
classNumber = []

In [12]:
# get the path of the traffic data
myList = os.listdir(folder_path)
print("View each classes in traffic folder :", myList, "\n")

# get the number of classes (number of folder)
lengthOfClasses = len(myList)
print("Total length of classes :", lengthOfClasses, "\n")


View each classes in traffic folder : ['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '4', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '5', '50', '51', '52', '53', '54', '55', '56', '57', '6', '7', '8', '9'] 

Total length of classes : 58 



### Iterate

In [13]:
print("Iterating to load images & classes\n")
# iterate 0 to length of classes (58)
for x in range(0, lengthOfClasses): # x is folder
    imagesList = os.listdir(os.path.join(folder_path, str(x))) # each (x) folder in trafficSignData 
    for img in imagesList:
        currentImage = cv2.imread(folder_path + "/" + str(x) + "/" + img) # trafficSignData --> x folder --> img = images
        if currentImage is not None:  # Check image is read
            currentImage = cv2.resize(currentImage, imageDimesions) # Resize to the dimensions tp 32 X 32 pixels
            images.append(currentImage)
            classNumber.append(x)
        else:
            print(f"It is wrong folder path {folder_path}")
    print(x, end=" ")

Iterating to load images & classes

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 

### Convert list to numpy array

In [14]:
# Convert list to numpy array
images = np.array(images)
classNumber = np.array(classNumber)

**Result**

In [15]:
print(images)
print(classNumber)

[[[[ 98 114 132]
   [ 98 114 132]
   [ 97 113 130]
   ...
   [ 78  90 106]
   [ 77  89 104]
   [ 76  89 103]]

  [[ 97 115 133]
   [ 98 113 132]
   [ 97 114 131]
   ...
   [ 82  92 105]
   [ 78  91 105]
   [ 81  91 104]]

  [[ 99 114 132]
   [ 98 114 131]
   [ 98 113 131]
   ...
   [ 83  92 105]
   [ 80  92 107]
   [ 83  91 105]]

  ...

  [[ 73  31 173]
   [ 97  81 133]
   [ 87 100 114]
   ...
   [ 75  84  90]
   [ 60  63  73]
   [ 74  82  91]]

  [[ 75  30 172]
   [ 88  70 141]
   [ 85  99 113]
   ...
   [ 74  85  92]
   [ 65  69  77]
   [ 74  83  91]]

  [[ 60  25 159]
   [ 73  52 140]
   [ 84  97 112]
   ...
   [ 74  83  92]
   [ 67  76  83]
   [ 74  83  89]]]


 [[[101 107 117]
   [ 98 117 139]
   [ 95 115 138]
   ...
   [ 81  97 115]
   [ 80  95 114]
   [ 81  94 111]]

  [[ 95 103 114]
   [ 97 117 140]
   [ 96 117 139]
   ...
   [ 82  97 113]
   [ 80  95 112]
   [ 81  94 110]]

  [[ 84  90 109]
   [ 98 118 137]
   [ 98 115 140]
   ...
   [ 83  97 113]
   [ 80  97 111]
   [ 81  93