### Import libraries

In [2]:
import numpy as np
import cv2
import os

**Parameter**

In [3]:
folder_path = "trafficSignData"
label_file = 'labels.csv'
imageDimesions = (32,32)

### Load the images and number of classes

In [4]:
images = []
classNumber = []

In [9]:
# get the path of the traffic data
myList = os.listdir(folder_path)
print("View each classes in traffic folder :", myList, "\n")

# get the number of classes (number of folder)
lengthOfClasses = len(myList)
print("Total length of classes :", lengthOfClasses, "\n")


View each classes in traffic folder : ['50', '57', '32', '35', '56', '51', '34', '33', '20', '18', '27', '9', '0', '11', '7', '29', '16', '42', '45', '6', '28', '17', '1', '10', '19', '26', '8', '21', '44', '43', '38', '36', '31', '54', '53', '30', '37', '39', '52', '55', '46', '41', '48', '24', '23', '4', '15', '3', '12', '49', '40', '47', '2', '13', '5', '14', '22', '25'] 

Total length of classes : 58 



### Iterate

In [6]:
print("Iterating to load images & classes\n")
# iterate 0 to length of classes (58)
for x in range(0, lengthOfClasses): # x is folder
    imagesList = os.listdir(os.path.join(folder_path, str(x))) # each (x) folder in trafficSignData 
    for img in imagesList:
        currentImage = cv2.imread(folder_path + "/" + str(x) + "/" + img) # trafficSignData --> x folder --> img = images
        if currentImage is not None:  # Check image is read
            currentImage = cv2.resize(currentImage, imageDimesions) # Resize to the dimensions tp 32 X 32 pixels
            images.append(currentImage)
            classNumber.append(x)
        else:
            print(f"It is wrong folder path {folder_path}")
    print(x, end=" ")

Iterating to load images & classes

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 

### Convert list to numpy array

In [7]:
# Convert list to numpy array
images = np.array(images)
classNumber = np.array(classNumber)

**Result**

In [8]:
print(images)
print(classNumber)

[[[[ 41  39  32]
   [ 38  39  31]
   [ 38  38  30]
   ...
   [155 153 151]
   [190 190 190]
   [192 192 192]]

  [[ 40  40  30]
   [ 38  38  32]
   [ 40  38  31]
   ...
   [151 150 147]
   [189 190 190]
   [189 189 189]]

  [[ 41  41  31]
   [ 39  39  30]
   [ 38  39  30]
   ...
   [145 146 141]
   [188 188 188]
   [185 185 185]]

  ...

  [[194 189 181]
   [195 190 176]
   [196 189 178]
   ...
   [121  49   7]
   [123  51   5]
   [121  50   8]]

  [[194 185 171]
   [193 184 173]
   [194 185 172]
   ...
   [165 158 151]
   [167 160 150]
   [167 162 153]]

  [[179 174 166]
   [179 174 166]
   [183 176 168]
   ...
   [125  55  13]
   [126  56  12]
   [127  55  13]]]


 [[[126  64  21]
   [138  91  58]
   [143 102  71]
   ...
   [165 155 142]
   [176 180 185]
   [162 166 170]]

  [[139 110  93]
   [154 140 129]
   [120  78  58]
   ...
   [164 159 153]
   [174 178 183]
   [169 171 171]]

  [[135  97  75]
   [145 114 101]
   [140 126 119]
   ...
   [157 162 164]
   [185 188 192]
   [179 179